buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
        maven {url 'https://maven.aliyun.com/repository/jcenter'}//注意，这里需要加上，否则拉不到walle:library，官方没提示
        maven {url 'https://maven.aliyun.com/repository/google'}//注意，这里需要加上，否则拉不到walle:library，官方没提示
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {url 'https://maven.aliyun.com/repository/jcenter'}//注意，这里需要加上，否则拉不到walle:library，官方没提示
        maven {url 'https://maven.aliyun.com/repository/google'}//注意，这里需要加上，否则拉不到walle:library，官方没提示
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
