import 'dart:io';

import 'package:get/get.dart';
import 'package:zpw/modules/vip/model/zpw_payBean.dart';
import 'package:zpw/modules/vip/model/zpw_vipBean.dart';

class VipState {
  late int itemIndex;
  late int type;
  late RxBool isCheck;
  late ZpwPayBean payBean;
  late ZpwVipBean vipBean;
  late int payKeyType;
  late int goodsId;
  late int isWx;
  late int isZfb;
  late RxInt statePay;
  ZpwVipBean normalVipBean = Platform.isIOS
      ? ZpwVipBean.fromJson({
          "id": 149,
          "channel": "AIIOS",
          "createTime": "2025-01-18 14:40:48",
          "projectId": 30,
          "vipList": [
            {
              "showRemark": "",
              "remark1": "最多人购买",
              "remark2": "年卡",
              "remark3": "198",
              "remark4": "原价468",
              "remark5": "",
              "remark6": "",
              "remark7": "",
              "remark8": "立即开通",
              "remark9": "周期会员到期自动续费，可退订",
              "remark10": "",
              "vipPriceId": 105,
              "isPayOne": null,
              "sortId": 0,
              "vipPriceOutput": {
                "id": 105,
                "showName": "普通支付-198.00元/365天",
                "price": 19800,
                "originalPrice": null,
                "vipTime": 365,
                "vipTimeType": "DAY",
                "vipName": null,
                "isZfbPay": 0,
                "isWxPay": 0,
                "isIosPay": 1,
                "payName": null,
                "iosProductId": "ai_year",
                "isWithdrawal": 0,
                "agreemenType": null,
                "agreemenPrice": null,
                "agreemenTime": null,
                "agreemenTimeType": null,
                "agreemenPayments": null,
                "collTime": null,
                "collTimeType": null,
                "agreemenPayNum": null,
                "decreaseMoney": null,
                "isDisposable": 0,
                "defaultZfbPayKeyType": null,
                "defaultPayKeyType": 2
              }
            },
            {
              "showRemark": "",
              "remark1": "",
              "remark2": "月卡",
              "remark3": "38",
              "remark4": "原价58",
              "remark5": "",
              "remark6": "",
              "remark7": "",
              "remark8": "立即开通",
              "remark9": "周期会员到期自动续费，可退订",
              "remark10": "",
              "vipPriceId": 107,
              "isPayOne": null,
              "sortId": 0,
              "vipPriceOutput": {
                "id": 107,
                "showName": "普通支付-38.00元/30天",
                "price": 3800,
                "originalPrice": null,
                "vipTime": 30,
                "vipTimeType": "DAY",
                "vipName": null,
                "isZfbPay": 0,
                "isWxPay": 0,
                "isIosPay": 1,
                "payName": null,
                "iosProductId": "ai_month",
                "isWithdrawal": 0,
                "agreemenType": null,
                "agreemenPrice": null,
                "agreemenTime": null,
                "agreemenTimeType": null,
                "agreemenPayments": null,
                "collTime": null,
                "collTimeType": null,
                "agreemenPayNum": null,
                "decreaseMoney": null,
                "isDisposable": 0,
                "defaultZfbPayKeyType": null,
                "defaultPayKeyType": 2
              }
            },
            {
              "showRemark": "",
              "remark1": "",
              "remark2": "季卡",
              "remark3": "98",
              "remark4": "原价128",
              "remark5": "",
              "remark6": "",
              "remark7": "",
              "remark8": "立即开通",
              "remark9": "周期会员到期自动续费，可退订",
              "remark10": "",
              "vipPriceId": 106,
              "isPayOne": null,
              "sortId": 0,
              "vipPriceOutput": {
                "id": 106,
                "showName": "普通支付-98.00元/90天",
                "price": 9800,
                "originalPrice": null,
                "vipTime": 90,
                "vipTimeType": "DAY",
                "vipName": null,
                "isZfbPay": 0,
                "isWxPay": 0,
                "isIosPay": 1,
                "payName": null,
                "iosProductId": "ai_quarter",
                "isWithdrawal": 0,
                "agreemenType": null,
                "agreemenPrice": null,
                "agreemenTime": null,
                "agreemenTimeType": null,
                "agreemenPayments": null,
                "collTime": null,
                "collTimeType": null,
                "agreemenPayNum": null,
                "decreaseMoney": null,
                "isDisposable": 0,
                "defaultZfbPayKeyType": null,
                "defaultPayKeyType": 2
              }
            }
          ],
          "vipPopList": [],
          "homePopList": [],
          "contentPopList": [
            {
              "showRemark": "",
              "remark1": "",
              "remark2": "2",
              "remark3": "返99元",
              "remark4": "",
              "remark5": "",
              "remark6": "",
              "remark7": "",
              "remark8": "",
              "remark9": "",
              "remark10": "",
              "vipPriceId": 13,
              "isPayOne": null,
              "sortId": 4,
              "vipPriceOutput": {
                "id": 13,
                "showName": "-直接签约-每期99.00元/30天-老账号价格-1时后扣款",
                "price": 0,
                "originalPrice": 0,
                "vipTime": 1,
                "vipTimeType": "DAY",
                "vipName": "会员开通",
                "isZfbPay": 1,
                "isWxPay": 0,
                "isIosPay": 0,
                "payName": "会员开通",
                "iosProductId": null,
                "isWithdrawal": 1,
                "agreemenType": 2,
                "agreemenPrice": 9900,
                "agreemenTime": 30,
                "agreemenTimeType": "DAY",
                "agreemenPayments": 24,
                "collTime": 1,
                "collTimeType": "HOUR",
                "agreemenPayNum": 3,
                "decreaseMoney": 1000,
                "isDisposable": 0,
                "defaultZfbPayKeyType": 0,
                "defaultPayKeyType": 0
              }
            },
            {
              "showRemark": "",
              "remark1": "",
              "remark2": "2",
              "remark3": "一键解锁·全部剧集",
              "remark4": "限时特惠",
              "remark5": "",
              "remark6": "免广告",
              "remark7": "试用结束后自动扣费99元/月",
              "remark8": "",
              "remark9": "",
              "remark10": "",
              "vipPriceId": 13,
              "isPayOne": null,
              "sortId": 3,
              "vipPriceOutput": {
                "id": 13,
                "showName": "-直接签约-每期99.00元/30天-老账号价格-1时后扣款",
                "price": 0,
                "originalPrice": 0,
                "vipTime": 1,
                "vipTimeType": "DAY",
                "vipName": "会员开通",
                "isZfbPay": 1,
                "isWxPay": 0,
                "isIosPay": 0,
                "payName": "会员开通",
                "iosProductId": null,
                "isWithdrawal": 1,
                "agreemenType": 2,
                "agreemenPrice": 9900,
                "agreemenTime": 30,
                "agreemenTimeType": "DAY",
                "agreemenPayments": 24,
                "collTime": 1,
                "collTimeType": "HOUR",
                "agreemenPayNum": 3,
                "decreaseMoney": 1000,
                "isDisposable": 0,
                "defaultZfbPayKeyType": 0,
                "defaultPayKeyType": 0
              }
            }
          ],
          "otherPopList": [
            {
              "showRemark": "拦截页",
              "remark1": "限时特惠",
              "remark2": "",
              "remark3": "",
              "remark4": "免费试用·解锁全部剧集",
              "remark5": "",
              "remark6": "试用结束自动扣费99元/月",
              "remark7": "2",
              "remark8": "1",
              "remark9": "",
              "remark10": "",
              "vipPriceId": 13,
              "isPayOne": null,
              "sortId": 0,
              "vipPriceOutput": {
                "id": 13,
                "showName": "-直接签约-每期99.00元/30天-老账号价格-1时后扣款",
                "price": 0,
                "originalPrice": 0,
                "vipTime": 1,
                "vipTimeType": "DAY",
                "vipName": "会员开通",
                "isZfbPay": 1,
                "isWxPay": 0,
                "isIosPay": 0,
                "payName": "会员开通",
                "iosProductId": null,
                "isWithdrawal": 1,
                "agreemenType": 2,
                "agreemenPrice": 9900,
                "agreemenTime": 30,
                "agreemenTimeType": "DAY",
                "agreemenPayments": 24,
                "collTime": 1,
                "collTimeType": "HOUR",
                "agreemenPayNum": 3,
                "decreaseMoney": 1000,
                "isDisposable": 0,
                "defaultZfbPayKeyType": 0,
                "defaultPayKeyType": 0
              }
            }
          ]
        })
      : ZpwVipBean.fromJson({
          "code": 100,
          "message": "成功",
          "data": {
            "id": 148,
            "channel": "AIJL300",
            "createTime": "2025-01-18 14:40:25",
            "projectId": 30,
            "vipList": [
              {
                "showRemark": "",
                "remark1": "最多人购买",
                "remark2": "免费试用",
                "remark3": "0.1",
                "remark4": "原价98",
                "remark5": "",
                "remark6": "",
                "remark7": "",
                "remark8": "立即开通",
                "remark9": "周期会员到期自动续费，可退订",
                "remark10": "",
                "vipPriceId": 83,
                "isPayOne": null,
                "sortId": 4,
                "vipPriceOutput": {
                  "id": 83,
                  "showName": "支付0.10元/1天-付款后签约-每期98.00元/30天-老账号价格-1时后扣款",
                  "price": 10,
                  "originalPrice": null,
                  "vipTime": 1,
                  "vipTimeType": "DAY",
                  "vipName": null,
                  "isZfbPay": 1,
                  "isWxPay": 0,
                  "isIosPay": 0,
                  "payName": null,
                  "iosProductId": null,
                  "isWithdrawal": 1,
                  "agreemenType": 1,
                  "agreemenPrice": 9800,
                  "agreemenTime": 30,
                  "agreemenTimeType": "DAY",
                  "agreemenPayments": 36,
                  "collTime": 1,
                  "collTimeType": "HOUR",
                  "agreemenPayNum": 3,
                  "decreaseMoney": 1000,
                  "isDisposable": 0,
                  "defaultZfbPayKeyType": 6,
                  "defaultPayKeyType": 6
                }
              },
              {
                "showRemark": "",
                "remark1": "",
                "remark2": "月卡",
                "remark3": "69",
                "remark4": "原价98",
                "remark5": "",
                "remark6": "",
                "remark7": "",
                "remark8": "立即开通",
                "remark9": "周期会员到期自动续费，可退订",
                "remark10": "",
                "vipPriceId": 79,
                "isPayOne": null,
                "sortId": 0,
                "vipPriceOutput": {
                  "id": 79,
                  "showName": "支付69.00元/1月-付款后签约-每期69.00元/30天-老账号价格-2天后扣款",
                  "price": 6900,
                  "originalPrice": null,
                  "vipTime": 1,
                  "vipTimeType": "MONTH",
                  "vipName": null,
                  "isZfbPay": 1,
                  "isWxPay": 0,
                  "isIosPay": 0,
                  "payName": null,
                  "iosProductId": null,
                  "isWithdrawal": 1,
                  "agreemenType": 1,
                  "agreemenPrice": 6900,
                  "agreemenTime": 30,
                  "agreemenTimeType": "DAY",
                  "agreemenPayments": 24,
                  "collTime": 2,
                  "collTimeType": "DAY",
                  "agreemenPayNum": 3,
                  "decreaseMoney": 500,
                  "isDisposable": 0,
                  "defaultZfbPayKeyType": null,
                  "defaultPayKeyType": 0
                }
              },
              {
                "showRemark": "",
                "remark1": "",
                "remark2": "年卡",
                "remark3": "129",
                "remark4": "原价198",
                "remark5": "",
                "remark6": "",
                "remark7": "",
                "remark8": "立即开通",
                "remark9": "周期会员到期自动续费，可退订",
                "remark10": "",
                "vipPriceId": 24,
                "isPayOne": null,
                "sortId": 0,
                "vipPriceOutput": {
                  "id": 24,
                  "showName": "支付89.00元/1年-付款后签约-每期89.00元/365天-新账号价格",
                  "price": 8900,
                  "originalPrice": null,
                  "vipTime": 1,
                  "vipTimeType": "YEAR",
                  "vipName": null,
                  "isZfbPay": 1,
                  "isWxPay": 0,
                  "isIosPay": 0,
                  "payName": null,
                  "iosProductId": null,
                  "isWithdrawal": 1,
                  "agreemenType": 1,
                  "agreemenPrice": 8900,
                  "agreemenTime": 365,
                  "agreemenTimeType": "DAY",
                  "agreemenPayments": 8900,
                  "collTime": null,
                  "collTimeType": null,
                  "agreemenPayNum": 3,
                  "decreaseMoney": null,
                  "isDisposable": 0,
                  "defaultZfbPayKeyType": 0,
                  "defaultPayKeyType": 0
                }
              }
            ],
            "vipPopList": [],
            "homePopList": [],
            "contentPopList": [
              {
                "showRemark": "",
                "remark1": "",
                "remark2": "2",
                "remark3": "返99元",
                "remark4": "",
                "remark5": "",
                "remark6": "",
                "remark7": "",
                "remark8": "",
                "remark9": "",
                "remark10": "",
                "vipPriceId": 13,
                "isPayOne": null,
                "sortId": 4,
                "vipPriceOutput": {
                  "id": 13,
                  "showName": "-直接签约-每期99.00元/30天-老账号价格-1时后扣款",
                  "price": 0,
                  "originalPrice": 0,
                  "vipTime": 1,
                  "vipTimeType": "DAY",
                  "vipName": "会员开通",
                  "isZfbPay": 1,
                  "isWxPay": 0,
                  "isIosPay": 0,
                  "payName": "会员开通",
                  "iosProductId": null,
                  "isWithdrawal": 1,
                  "agreemenType": 2,
                  "agreemenPrice": 9900,
                  "agreemenTime": 30,
                  "agreemenTimeType": "DAY",
                  "agreemenPayments": 24,
                  "collTime": 1,
                  "collTimeType": "HOUR",
                  "agreemenPayNum": 3,
                  "decreaseMoney": 1000,
                  "isDisposable": 0,
                  "defaultZfbPayKeyType": 0,
                  "defaultPayKeyType": 0
                }
              },
              {
                "showRemark": "",
                "remark1": "",
                "remark2": "2",
                "remark3": "一键解锁·全部剧集",
                "remark4": "限时特惠",
                "remark5": "",
                "remark6": "免广告",
                "remark7": "试用结束后自动扣费99元/月",
                "remark8": "",
                "remark9": "",
                "remark10": "",
                "vipPriceId": 13,
                "isPayOne": null,
                "sortId": 3,
                "vipPriceOutput": {
                  "id": 13,
                  "showName": "-直接签约-每期99.00元/30天-老账号价格-1时后扣款",
                  "price": 0,
                  "originalPrice": 0,
                  "vipTime": 1,
                  "vipTimeType": "DAY",
                  "vipName": "会员开通",
                  "isZfbPay": 1,
                  "isWxPay": 0,
                  "isIosPay": 0,
                  "payName": "会员开通",
                  "iosProductId": null,
                  "isWithdrawal": 1,
                  "agreemenType": 2,
                  "agreemenPrice": 9900,
                  "agreemenTime": 30,
                  "agreemenTimeType": "DAY",
                  "agreemenPayments": 24,
                  "collTime": 1,
                  "collTimeType": "HOUR",
                  "agreemenPayNum": 3,
                  "decreaseMoney": 1000,
                  "isDisposable": 0,
                  "defaultZfbPayKeyType": 0,
                  "defaultPayKeyType": 0
                }
              }
            ],
            "otherPopList": [
              {
                "showRemark": "拦截页",
                "remark1": "限时特惠",
                "remark2": "",
                "remark3": "",
                "remark4": "免费试用·解锁全部剧集",
                "remark5": "",
                "remark6": "试用结束自动扣费99元/月",
                "remark7": "2",
                "remark8": "1",
                "remark9": "",
                "remark10": "",
                "vipPriceId": 13,
                "isPayOne": null,
                "sortId": 0,
                "vipPriceOutput": {
                  "id": 13,
                  "showName": "-直接签约-每期99.00元/30天-老账号价格-1时后扣款",
                  "price": 0,
                  "originalPrice": 0,
                  "vipTime": 1,
                  "vipTimeType": "DAY",
                  "vipName": "会员开通",
                  "isZfbPay": 1,
                  "isWxPay": 0,
                  "isIosPay": 0,
                  "payName": "会员开通",
                  "iosProductId": null,
                  "isWithdrawal": 1,
                  "agreemenType": 2,
                  "agreemenPrice": 9900,
                  "agreemenTime": 30,
                  "agreemenTimeType": "DAY",
                  "agreemenPayments": 24,
                  "collTime": 1,
                  "collTimeType": "HOUR",
                  "agreemenPayNum": 3,
                  "decreaseMoney": 1000,
                  "isDisposable": 0,
                  "defaultZfbPayKeyType": 0,
                  "defaultPayKeyType": 0
                }
              }
            ]
          }
        });
  VipState() {
    payBean = ZpwPayBean();
    vipBean = ZpwVipBean();
    isCheck = false.obs;
    itemIndex = 0;
    payKeyType = 0;
    goodsId = 0;
    isWx = 0;
    isZfb = 0;
    type = 0;
    statePay = 0.obs;
  }
}
